### ISSUE TITLE
Move some enums from Enums folder

### ISSUE THREAD

**Issue by JanWielgus** [ColyberCompany/ColyberFlightController#70]
I think that for example it will be better for FlightModeTypes to be insinde the FlightMode class.
Same for AxisType and SensorTypes.

**Comment by lilooraf** [comment]
Hi @JanWielgus, can I try it ?

**Comment by JanWielgus** [comment]
@lilooraf of course. This is standard PlatformIO project. If you will have trouble to open and compile it, let me know.
This issue about moving some (not all) enums from Enums folder, to the appropriate classes (just nested enums inside this classes).

FlightModeTypes into FlightMode class.
SensorTypes into Sensor class.
Do not change AxisType enum.

And then change all usages of those enums in code that code will compile.

**Comment by lilooraf** [comment]
Thanks, I'm use to makefiles so maybe how to compile it

**Comment by lilooraf** [comment]
#71
